name: Build Plugin
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub global activate hetu_script_dev_tools
      - run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      - run: sudo apt-get install -y zip
      - run: make compile
      - run: make archive
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          files: build/plugin.smplug